### ISSUE TITLE
Suppressing JavaExceptions

### ISSUE THREAD

**Issue by caspervdw** [CellProfiler/python-javabridge#37]
For a project, I want to list all methods of a JWrapped object that do not throw an error. I do this as follows:

    for name, method in JWrapped_object.methods.iteritems():
        try:
            fn = getattr(JWrapped_object, name)
            field = fn(*args)
            # some action here if java didn't throw an error
        except javabridge.JavaException:
            pass

This works nicely, except for the fact that in commandline there is a lot of JavaExceptions printed. I can't figure out how to suppress this printing. I tried to set the java log level to OFF like this (similar to `bioformats.init_logger()`):
    
    javabridge.start_vm()
    javabridge.static_call("org/apache/log4j/BasicConfigurator",
                           "configure", "()V")
    log4j_logger = javabridge.static_call("org/apache/log4j/Logger",
                                      "getRootLogger",
                                      "()Lorg/apache/log4j/Logger;")
    warn_level = javabridge.get_static_field("org/apache/log4j/Level", 'OFF',
                                         "Lorg/apache/log4j/Level;")
    javabridge.call(log4j_logger, "setLevel", "(Lorg/apache/log4j/Level;)V",
                warn_level)

With no effect. Also I tried to redirect the `stdout` and `stderr`, also with no effect. Does anybody know how to suppress these errors?

**Comment by LeeKamentsky** [comment]
The best way perhaps is to supply a configuration file (see http://logging.apache.org/log4j/2.x/manual/configuration.html for instance). You can then start the javabridge with an argument of "-Dlog4j.configurationFile=*filename.xml*" to get it to use that file straight off. There's some chance that you're seeing Python logging (you'd see a Python stack instead of a Java one) and you might try turning logging off there too. If you're using bioformats, you may need to monkey-patch it to keep it from undoing your work (didn't try this out, but I think it would work):

    import bioformats
    def init_logger(self):
         pass
    bioformats.init_logger = init_logger
    # Initialize javabridge after monkey-patching bioformats

**Comment by caspervdw** [comment]
Thanks for the response. My exceptions look like this. This is a Java stack. I know very little about java, but this formatting doesn't look like the `log4j` messages I got before. Is it possible that log4j has nothing to do with this?

    Exception in thread "Thread-0" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at ome.xml.model.OME.getPlate(OME.java:492)
        at ome.xml.meta.OMEXMLMetadataImpl.getWellAnnotationRef(OMEXMLMetadataImpl.java:5355)

**Comment by caspervdw** [comment]
I've been trying to adjust the standard java output stream, using:

    import javabridge as J
    J.start_vm()
    Joutputstream = J.make_instance('java/io/ByteArrayOutputStream', "()V")
    Jprintstream = J.make_instance('java/io/PrintStream', 
                                   "(Ljava/io/OutputStream;)V", Joutputstream)
    J.static_call('Ljava/lang/System;', "setErr", 
                           "(Ljava/io/PrintStream;)V", Jprintstream)
    try:
        J.run_script('this/raises/an/exception;')
    except:
        pass

This reduces the printed error to: `Exception in thread "Thread-0"`. It seems I'm in the right direction, but I also need to remove this line from the console. Anybody an idea to stop the printing of this line?

**Comment by LeeKamentsky** [comment]
Idea, but not definite - maybe "Exception in thread "Thread-0"" is being sent to stdout? Can you redirect both of them? I just tried it, it seems to work (whew).

    Joutputstream = J.make_instance('java/io/ByteArrayOutputStream', "()V")
    Jprintstream = J.make_instance('java/io/PrintStream', 
                                   "(Ljava/io/OutputStream;)V", Joutputstream)
    J.static_call('Ljava/lang/System;', "setOut", 
                           "(Ljava/io/PrintStream;)V", Jprintstream)

**Comment by caspervdw** [comment]
I tried that too, but without success. It appears that java prints the stack to system.err and somehow the exception notification comes through differently.

I have read something about `java.lang.thread.UncaughtExceptionHandler`, you can set a custom handler. Maybe this will overwrite the printing. I will try to figure out how this works.

**Comment by caspervdw** [comment]
Ok I tried resetting the `uncaughtexceptionhandler` like this, but apparently I am doing something wrong or there is some custom exception handler inside java at work.

    newhandler = J.run_script("""new java.lang.Thread.UncaughtExceptionHandler() {
        uncaughtException: function(t, e) {
        }
     };""")
    current_thread = J.static_call("java/lang/Thread", "currentThread", "()Ljava/lang/Thread;")
    J.call(current_thread, "setUncaughtExceptionHandler", 
                       "(Ljava/lang/Thread$UncaughtExceptionHandler;)V", newhandler)
    J.static_call('Ljava/lang/Thread;', "setDefaultUncaughtExceptionHandler", 
                       "(Ljava/lang/Thread$UncaughtExceptionHandler;)V", newhandler)

The following code shows (on my win64 commandline) that both system.err and system.out are correctly redirected and accessible from python (could be a handy addition to javabridge?).
But it cannot suppress the printing of the line `Exception in thread "Thread-0"`. Can you reproduce this?


    import javabridge as J
    
    try:
        J.start_vm()
        java_stack = J.make_instance('java/io/ByteArrayOutputStream', "()V")
        java_stack_ps = J.make_instance('java/io/PrintStream', 
                                       "(Ljava/io/OutputStream;)V", java_stack)
        J.static_call('Ljava/lang/System;', "setErr", 
                      '(Ljava/io/PrintStream;)V', java_stack_ps)
        java_out = J.make_instance('java/io/ByteArrayOutputStream', "()V")
        java_out_ps = J.make_instance('java/io/PrintStream', 
                                       "(Ljava/io/OutputStream;)V", java_out)
        J.static_call('Ljava/lang/System;', "setOut", 
                  '(Ljava/io/PrintStream;)V', java_out_ps)
        J.run_script('java.lang.System.out.println("This is java system.out!");')
        try:
            J.run_script('this/raises/an/exception;')
        except J.JavaException:
            print('\n\nJava stdErr: ' + J.to_string(java_stack))
    finally:
        print('\n\nJava stdOut: ' + J.to_string(java_out)) 
        J.kill_vm()
