### ISSUE TITLE
Call Python from Java

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/python-javabridge#38]
Implement a JNI class that can execute a CPython script and can start the CPython interpreter from a Java process.

**Comment by LeeKamentsky** [comment]
Implemented by ff1b9822e71eda9279571da8b0f815e8dc86a826

org.cellprofiler.javabridge.CPython.exec() makes CPython accessible from Java.

**Comment by LeeKamentsky** [comment]
Build for Linux and Mac still needs to be done, Python 2.6 does not have capsules, so that needs to be reworked.

**Comment by ljosa** [comment]
I think we use Python 2.7 everywhere.

**Comment by LeeKamentsky** [comment]
Do we support Centos 6's Python 2.6?

**Comment by ljosa** [comment]
On Tue, Jan 13, 2015 at 3:57 PM, LeeKamentsky <notifications@github.com>
wrote:

> Do we support Centos 6's Python 2.6?


No, we build our own Python under /usr/cellprofiler for CentOS 6. I think
CellProfiler has required 2.7 for at least a couple of years.

Vebjorn

**Comment by LeeKamentsky** [comment]
Builds and installs on Mac and Linux.
