### ISSUE TITLE
Visual Studio 2008 Dependancy

### ISSUE THREAD

**Issue by DNeems** [CellProfiler/python-javabridge#42]
I am trying to install javabridge on my system but their is a dependency on Visual Studio 2008.  I have on my system the newest version of Visual Studio 2013 installed.  Is this not sufficient to install javabridge?  I cannot find an old distribution of visual studio 2008 to get beyond this point.
Thanks for the help

**Comment by LeeKamentsky** [comment]
Python 2.7 itself has the dependency on Visual Studio 2008 or the Microsoft
SDK which is freely available. I use the Microsoft SDK myself (
http://www.microsoft.com/en-us/download/details.aspx?id=8279). The trick
here is to use the command-line tools provided by it and to define the
environment variables, "MSSdk=1" and "DISTUTILS_USE_SDK=1". After that,
everything should compile.

The Javabridge must not only be built against a particular version of
Python. It also must match the version of Numpy on your system. We could
create binary installers for Windows, but they would have to be
Numpy-specific. Nevertheless, it might be useful for us to build some of
them so that the SDK and JDK would not be needed for installation.

**Comment by DNeems** [comment]
Thanks so much for the pointer.  This help allowed me to get further along in the compiling unfortunately I encountered another error.  See text below.  Also I don't think this should matter but since it might I will share.  I do not know how to set environmental variables with command-line tools so I did it using the interface under my computer>Properties> Advanced System Settings > Advanced > Environmental Variables.  Which I think it functionally the same.  Here is the error report 
Collecting javabridge
  Using cached javabridge-1.0.9.tar.gz
    Using jdk_home = C:\Users\Daniel\Downloads\_temp_matlab_R2014a_win64\sys\java\jre\win64\jre\bin\server
Requirement already satisfied (use --upgrade to upgrade): numpy in c:\users\daniel\appdata\local\enthought\canopy\user\l
ib\site-packages (from javabridge)
Installing collected packages: javabridge
  Running setup.py install for javabridge
    Using jdk_home = C:\Users\Daniel\Downloads\_temp_matlab_R2014a_win64\sys\java\jre\win64\jre\bin\server
    building 'javabridge._javabridge' extension
    cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\Daniel\AppData\Local\Enthought\Canopy\User\lib\site-packages\
numpy\core\include -IC:\Users\Daniel\Downloads\_temp_matlab_R2014a_win64\sys\java\jre\win64\jre\bin\server\include -IC:\
Users\Daniel\Downloads\_temp_matlab_R2014a_win64\sys\java\jre\win64\jre\bin\server\include\win32 -IC:\Users\Daniel\AppDa
ta\Local\Enthought\Canopy\App\appdata\canopy-1.5.2.2785.win-x86_64\include -IC:\Users\Daniel\AppData\Local\Enthought\Can
opy\User\PC /Tc_javabridge.c /Fobuild\temp.win-amd64-2.7\Release\_javabridge.obj
    error: command 'cl.exe' failed: No such file or directory
    Complete output from command C:\Users\Daniel\AppData\Local\Enthought\Canopy\User\Scripts\python.exe -c "import setup
tools, tokenize;__file__='c:\\users\\daniel\\appdata\\local\\temp\\pip-build-ak0ztu\\javabridge\\setup.py';exec(compile(
getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\da
niel\appdata\local\temp\pip-pvqmby-record\install-record.txt --single-version-externally-managed --compile --install-hea
ders C:\Users\Daniel\AppData\Local\Enthought\Canopy\User\include\site\python2.7:
    Using jdk_home = C:\Users\Daniel\Downloads\_temp_matlab_R2014a_win64\sys\java\jre\win64\jre\bin\server

    running install

    running build

    running build_py

    creating build

    creating build\lib.win-amd64-2.7

    creating build\lib.win-amd64-2.7\javabridge

    copying javabridge\jutil.py -> build\lib.win-amd64-2.7\javabridge

    copying javabridge\locate.py -> build\lib.win-amd64-2.7\javabridge

    copying javabridge\noseplugin.py -> build\lib.win-amd64-2.7\javabridge

    copying javabridge\wrappers.py -> build\lib.win-amd64-2.7\javabridge

    copying javabridge\_version.py -> build\lib.win-amd64-2.7\javabridge

    copying javabridge\__init__.py -> build\lib.win-amd64-2.7\javabridge

    creating build\lib.win-amd64-2.7\javabridge\jars

    copying javabridge\jars\rhino-1.7R4.jar -> build\lib.win-amd64-2.7\javabridge\jars

    copying javabridge\jars\runnablequeue.jar -> build\lib.win-amd64-2.7\javabridge\jars

    copying javabridge\jars\test.jar -> build\lib.win-amd64-2.7\javabridge\jars

    running build_ext

    running build_java

    building 'javabridge._javabridge' extension

    creating build\temp.win-amd64-2.7

    creating build\temp.win-amd64-2.7\Release

    cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\Daniel\AppData\Local\Enthought\Canopy\User\lib\site-packages\
numpy\core\include -IC:\Users\Daniel\Downloads\_temp_matlab_R2014a_win64\sys\java\jre\win64\jre\bin\server\include -IC:\
Users\Daniel\Downloads\_temp_matlab_R2014a_win64\sys\java\jre\win64\jre\bin\server\include\win32 -IC:\Users\Daniel\AppDa
ta\Local\Enthought\Canopy\App\appdata\canopy-1.5.2.2785.win-x86_64\include -IC:\Users\Daniel\AppData\Local\Enthought\Can
opy\User\PC /Tc_javabridge.c /Fobuild\temp.win-amd64-2.7\Release\_javabridge.obj

    error: command 'cl.exe' failed: No such file or directory

    ----------------------------------------
    Command "C:\Users\Daniel\AppData\Local\Enthought\Canopy\User\Scripts\python.exe -c "import setuptools, tokenize;__fi
le__='c:\\users\\daniel\\appdata\\local\\temp\\pip-build-ak0ztu\\javabridge\\setup.py';exec(compile(getattr(tokenize, 'o
pen', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\daniel\appdata\local\t
emp\pip-pvqmby-record\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\Daniel
\AppData\Local\Enthought\Canopy\User\include\site\python2.7" failed with error code 1 in c:\users\daniel\appdata\local\temp\pip-build-ak0ztu\javabridge

Any Ideas what might be causing it.  I apologize in advance for my novice in the field if it is something simple. Thanks again

**Comment by LeeKamentsky** [comment]
It looks like you might not have run the setup script in a Windows SDK command shell. On my machine, that's in the Start menu: "All Programs/Microsoft Windows SDK v7.0/CMD Shell.

After that, CD to the directory you used to check out the Javabridge and do:

    > set MSSdk=1
    > set DISTUTILS_USE_SDK=1
    > python setup.py install

**Comment by DNeems** [comment]
Got in installed, thanks.  Your suggestion of running it via python setup.py install also did not work, however using pip install within the Windows SDK command shell did.  Thanks
