### ISSUE TITLE
Modify location of registry search for Java

### ISSUE THREAD

**Issue by braymp** [CellProfiler/python-javabridge#51]
While diagnosing why Tracer crashes on Win8 x64, I found that the search for Java in locate.py [references](https://github.com/CellProfiler/python-javabridge/blob/master/javabridge/locate.py#L92) the current Java version as 'SOFTWARE\\JavaSoft\\Java Runtime Environment'. This key doesn't seem to exist in Win8 x64 and the search fails. I think this may have been written for Win x86.

This [page](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724072%28v=vs.85%29.aspx) indicates that the proper location should be 'SOFTWARE\\Wow6432Node\\JavaSoft\\Java Runtime Environment'. This exists in both Win7 and Win8 x64.

**Comment by LeeKamentsky** [comment]
You should make sure you have the 64-bit JRE installed. I am guessing that if you examine 'SOFTWARE\Wow6432Node\JavaSoft\Java Runtime Environment\1.X\JavaHome', it will be pointing at 'C:\Program Files (x86)\Java\jreX' indicating that it's 32-bit.

**Comment by braymp** [comment]
Well, that was stupid. Closing.
