### ISSUE TITLE
Installing javabridge fails with gcc error while gcc is available

### ISSUE THREAD

**Issue by narasing** [CellProfiler/python-javabridge#52]
As you can see I have gcc available.  I have gcc44 & created alias in ~/.bashrc to point to gcc44 & gcc -v works but I get this error. Please help.
$  $HOME/Enthought/Canopy_64bit/User/bin/python2.7 setup.py install
running install
running bdist_egg
running egg_info
writing requirements to javabridge.egg-info/requires.txt
writing javabridge.egg-info/PKG-INFO
writing top-level names to javabridge.egg-info/top_level.txt
writing dependency_links to javabridge.egg-info/dependency_links.txt
writing entry points to javabridge.egg-info/entry_points.txt
reading manifest file 'javabridge.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching '*.pyx'
writing manifest file 'javabridge.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
javac -source 6 -target 6 java/org/cellprofiler/runnablequeue/RunnableQueue.java
javac -source 6 -target 6 java/org/cellprofiler/javabridge/test/RealRect.java
javac -source 6 -target 6 java/org/cellprofiler/javabridge/CPython.java java/org/cellprofiler/javabridge/CPythonInvocationHandler.java
Note: java/org/cellprofiler/javabridge/CPythonInvocationHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
building 'javabridge._javabridge' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -O2 -fPIC -I/home/sysnyqcestg/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/core/include -I/usr/java/include -I/usr/java/include/linux -I/home/sysnyqcestg/Canopy/appdata/canopy-1.5.1.2730.rh5-x86_64/include/python2.7 -c _javabridge.c -o build/temp.linux-x86_64-2.7/_javabridge.o
unable to execute gcc: No such file or directory
error: command 'gcc' failed with exit status 1
$ gcc -v
Using built-in specs.
Target: x86_64-redhat-linux6E
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --disable-gnu-unique-object --with-as=/usr/libexec/binutils220/as --enable-languages=c,c++,fortran --disable-libgcj --with-mpfr=/builddir/build/BUILD/gcc-4.4.7-20120601/obj-x86_64-redhat-linux6E/mpfr-install/ --with-ppl=/builddir/build/BUILD/gcc-4.4.7-20120601/obj-x86_64-redhat-linux6E/ppl-install --with-cloog=/builddir/build/BUILD/gcc-4.4.7-20120601/obj-x86_64-redhat-linux6E/cloog-install --with-tune=generic --with-arch_32=i586 --build=x86_64-redhat-linux6E
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)
$

**Comment by LeeKamentsky** [comment]
I am not so much of an expert when it comes to Linux, but my first guess is that you need a soft link instead of an alias. Distutils and Cython probably use "subprocess" to launch gcc directly, bypassing your alias.

Could you do the following to confirm that your gcc is accessible from Python and to demonstrate that the problem is with the alias?

I expect this one to produce an error:

    python -c "import subprocess;subprocess.Popen(['gcc', '-v']).communicate()"

I expect this one to work:

    python -c "import subprocess;subprocess.Popen(['gcc -v'],shell=True).communicate()"

**Comment by narasing** [comment]
Thanks for quickfire reply. it turns out, I tried using alias to point gcc44 to gcc and looks like that caused the issue. 

However, when I able to get this run, I am getting whole bunch of compilation errors: 
building 'javabridge._javabridge' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -O2 -fPIC -I/home/sysnyqcestg/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/core/include -I/usr/java/include -I/usr/java/include/linux -I/home/sysnyqcestg/Canopy/appdata/canopy-1.5.1.2730.rh5-x86_64/include/python2.7 -c _javabridge.c -o build/temp.linux-x86_64-2.7/_javabridge.o
In file included from /home/sysnyqcestg/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1761,
                 from /home/sysnyqcestg/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /home/sysnyqcestg/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from _javabridge.c:346:
/home/sysnyqcestg/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
_javabridge.c:348:17: error: jni.h: No such file or directory
In file included from _javabridge.c:349:
mac_javabridge_utils.h:36: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'int'
mac_javabridge_utils.h:47: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'void'
mac_javabridge_utils.h:55: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'void'
mac_javabridge_utils.h:63: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'void'
mac_javabridge_utils.h:71: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'void'
mac_javabridge_utils.h:79: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'void'
mac_javabridge_utils.h:88: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'int'
_javabridge.c:861: error: expected specifier-qualifier-list before 'jobject'
_javabridge.c:875: error: expected specifier-qualifier-list before 'jclass'
_javabridge.c:888: error: expected specifier-qualifier-list before 'jmethodID'
_javabridge.c:903: error: expected specifier-qualifier-list before 'jfieldID'
_javabridge.c:918: error: expected specifier-qualifier-list before 'JavaVM'
_javabridge.c:931: error: expected specifier-qualifier-list before 'JNIEnv'
_javabridge.c:1221: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__Pyx_PyInt_As_jbyte'
_javabridge.c:1223: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__Pyx_PyInt_As_jchar'
_javabridge.c:1225: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__Pyx_PyInt_As_jshort'
_javabridge.c:1227: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__Pyx_PyInt_As_jint'
_javabridge.c:1229: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__Pyx_PyInt_As_jlong'

saw one of your replies on jni.h not being in java path.I will verify that. Could you please confirm if  numpy error is substantial? if so, which version should I upgrade to?

Thanks

**Comment by LeeKamentsky** [comment]
The numpy error is no big deal. We use 1.9.0 here. I am guessing you need to install the JDK and maybe set JAVA_HOME to point at it. See:
http://pythonhosted.org/javabridge/installation.html#linux

**Comment by narasing** [comment]
I had to set the JAVA_HOME & I am getting this.
/home/sysnyqcestg/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
_javabridge.c: In function '__pyx_pf_11_javabridge_9JB_Object_2__repr__':
_javabridge.c:3982: warning: cast from pointer to integer of different size
_javabridge.c: In function '__pyx_pf_11_javabridge_9JB_Object_6addr':
_javabridge.c:4227: warning: cast from pointer to integer of different size
_javabridge.c: In function '__pyx_pf_11_javabridge_8JB_Class_2__repr__':
_javabridge.c:4352: warning: cast from pointer to integer of different size
_javabridge.c: In function '__pyx_pf_11_javabridge_13__JB_MethodID_2__repr__':
_javabridge.c:4498: warning: cast from pointer to integer of different size
_javabridge.c: In function '__pyx_pf_11_javabridge_12__JB_FieldID_2__repr__':
_javabridge.c:4652: warning: cast from pointer to integer of different size
_javabridge.c: In function '__pyx_pf_11_javabridge_6JB_Env_118get_string':
_javabridge.c:17635: warning: cast from pointer to integer of different size
_javabridge.c: In function '__pyx_pf_11_javabridge_6JB_Env_120get_string_utf':
_javabridge.c:17763: warning: cast from pointer to integer of different size
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -O2 -fPIC -I/home/sysnyqcestg/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/core/include -I/usr/java/default/include -I/usr/java/default/include/linux -I/home/sysnyqcestg/Canopy/appdata/canopy-1.5.1.2730.rh5-x86_64/include/python2.7 -c _javabridge_nomac.c -o build/temp.linux-x86_64-2.7/_javabridge_nomac.o
gcc -pthread -shared -Wl,-rpath,$ORIGIN/../lib -g -L/home/sysnyqcestg/Canopy/appdata/canopy-1.5.1.2730.rh5-x86_64/lib build/temp.linux-x86_64-2.7/_javabridge.o build/temp.linux-x86_64-2.7/_javabridge_nomac.o -L/usr/java/default/jre/lib/amd64/client -L/usr/java/default/jre/lib/amd64/server -L/usr/java/default/jre/lib/i386/client -L/usr/java/default/jre/lib/i386/server -L/home/sysnyqcestg/Canopy/appdata/canopy-1.5.1.2730.rh5-x86_64/lib -Wl,-R/usr/java/default/jre/lib/amd64/client -Wl,-R/usr/java/default/jre/lib/amd64/server -Wl,-R/usr/java/default/jre/lib/i386/client -Wl,-R/usr/java/default/jre/lib/i386/server -ljvm -lpython2.7 -o build/lib.linux-x86_64-2.7/javabridge/_javabridge.so
building java2cpython library
creating build/temp.linux-x86_64-2.7/java
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -O2 -fPIC -I/home/builder/jenkins/workspace/Python_Masters/ARCH/x86_64/label/Linux/core/include/python2.7 -Ijava -I/usr/java/default/include -I/usr/java/default/include/linux -I/home/sysnyqcestg/Canopy/appdata/canopy-1.5.1.2730.rh5-x86_64/include/python2.7 -c java/org_cellprofiler_javabridge_CPython.c -o build/temp.linux-x86_64-2.7/java/org_cellprofiler_javabridge_CPython.o
gcc -pthread -shared -Wl,-rpath,$ORIGIN/../lib -g -L/home/sysnyqcestg/Canopy/appdata/canopy-1.5.1.2730.rh5-x86_64/lib build/temp.linux-x86_64-2.7/java/org_cellprofiler_javabridge_CPython.o -L/home/builder/jenkins/workspace/Python_Masters/ARCH/x86_64/label/Linux/core/lib -L/home/sysnyqcestg/Canopy/appdata/canopy-1.5.1.2730.rh5-x86_64/lib -o build/lib.linux-x86_64-2.7/javabridge/jars/libjava2cpython.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/javabridge
copying build/lib.linux-x86_64-2.7/javabridge/_javabridge.so -> build/bdist.linux-x86_64/egg/javabridge
creating build/bdist.linux-x86_64/egg/javabridge/tests
copying build/lib.linux-x86_64-2.7/javabridge/tests/test_wrappers.py -> build/bdist.linux-x86_64/egg/javabridge/tests
copying build/lib.linux-x86_64-2.7/javabridge/tests/test_cpython.py -> build/bdist.linux-x86_64/egg/javabridge/tests
copying build/lib.linux-x86_64-2.7/javabridge/tests/__init__.py -> build/bdist.linux-x86_64/egg/javabridge/tests
copying build/lib.linux-x86_64-2.7/javabridge/tests/test_javabridge.py -> build/bdist.linux-x86_64/egg/javabridge/tests
copying build/lib.linux-x86_64-2.7/javabridge/tests/test_jutil.py -> build/bdist.linux-x86_64/egg/javabridge/tests
copying build/lib.linux-x86_64-2.7/javabridge/_version.py -> build/bdist.linux-x86_64/egg/javabridge
copying build/lib.linux-x86_64-2.7/javabridge/__init__.py -> build/bdist.linux-x86_64/egg/javabridge
copying build/lib.linux-x86_64-2.7/javabridge/noseplugin.py -> build/bdist.linux-x86_64/egg/javabridge
copying build/lib.linux-x86_64-2.7/javabridge/locate.py -> build/bdist.linux-x86_64/egg/javabridge
copying build/lib.linux-x86_64-2.7/javabridge/jutil.py -> build/bdist.linux-x86_64/egg/javabridge
creating build/bdist.linux-x86_64/egg/javabridge/jars
copying build/lib.linux-x86_64-2.7/javabridge/jars/rhino-1.7R4.jar -> build/bdist.linux-x86_64/egg/javabridge/jars
copying build/lib.linux-x86_64-2.7/javabridge/jars/runnablequeue.jar -> build/bdist.linux-x86_64/egg/javabridge/jars
copying build/lib.linux-x86_64-2.7/javabridge/jars/libjava2cpython.so -> build/bdist.linux-x86_64/egg/javabridge/jars
copying build/lib.linux-x86_64-2.7/javabridge/jars/cpython.jar -> build/bdist.linux-x86_64/egg/javabridge/jars
copying build/lib.linux-x86_64-2.7/javabridge/jars/test.jar -> build/bdist.linux-x86_64/egg/javabridge/jars
copying build/lib.linux-x86_64-2.7/javabridge/wrappers.py -> build/bdist.linux-x86_64/egg/javabridge
byte-compiling build/bdist.linux-x86_64/egg/javabridge/tests/test_wrappers.py to test_wrappers.pyc
byte-compiling build/bdist.linux-x86_64/egg/javabridge/tests/test_cpython.py to test_cpython.pyc
byte-compiling build/bdist.linux-x86_64/egg/javabridge/tests/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/javabridge/tests/test_javabridge.py to test_javabridge.pyc
byte-compiling build/bdist.linux-x86_64/egg/javabridge/tests/test_jutil.py to test_jutil.pyc
byte-compiling build/bdist.linux-x86_64/egg/javabridge/_version.py to _version.pyc
byte-compiling build/bdist.linux-x86_64/egg/javabridge/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/javabridge/noseplugin.py to noseplugin.pyc
byte-compiling build/bdist.linux-x86_64/egg/javabridge/locate.py to locate.pyc
byte-compiling build/bdist.linux-x86_64/egg/javabridge/jutil.py to jutil.pyc
byte-compiling build/bdist.linux-x86_64/egg/javabridge/wrappers.py to wrappers.pyc
creating stub loader for javabridge/_javabridge.so
byte-compiling build/bdist.linux-x86_64/egg/javabridge/_javabridge.py to _javabridge.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying javabridge.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying javabridge.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying javabridge.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying javabridge.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying javabridge.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying javabridge.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
javabridge.jutil: module MAY be using inspect.stack
javabridge.__init__: module references __file__
creating dist
creating 'dist/javabridge-1.0.11-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing javabridge-1.0.11-py2.7-linux-x86_64.egg
creating /home/sysnyqcestg/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/javabridge-1.0.11-py2.7-linux-x86_64.egg
Extracting javabridge-1.0.11-py2.7-linux-x86_64.egg to /home/sysnyqcestg/Enthought/Canopy_64bit/User/lib/python2.7/site-packages
Adding javabridge 1.0.11 to easy-install.pth file

Installed /home/sysnyqcestg/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/javabridge-1.0.11-py2.7-linux-x86_64.egg
Processing dependencies for javabridge==1.0.11
Searching for numpy==1.8.1
Best match: numpy 1.8.1
Adding numpy 1.8.1 to easy-install.pth file
Installing f2py script to /home/sysnyqcestg/Enthought/Canopy_64bit/User/bin

Using /home/sysnyqcestg/Enthought/Canopy_64bit/User/lib/python2.7/site-packages
Finished processing dependencies for javabridge==1.0.11


Does this mean, its successfully installed & I can go play with it?

Thanks you!!

**Comment by LeeKamentsky** [comment]
Looks pretty good. Try something like:

    import javabridge
    javabridge.start_vm()
    print javabridge.JClassWrapper("java.lang.String").format("Hello, %s", "world")
    javabridge.kill_vm()

and then read the manual :smirk_cat:

**Comment by narasing** [comment]
Thank you!! I am attempting substantial work, so will be spending quite a time on manual!! Thank you!!
