### ISSUE TITLE
Unable to specify new directory in classpath using class_path & unable to add -Xdebug as an arg.

### ISSUE THREAD

**Issue by narasing** [CellProfiler/python-javabridge#53]
Hi, 

 I have tried to add a directory using class_path either passing path or using os.path.
javabridge.start_vm(class_path=[os.path.realpath(os.path.join(os.path.dirname(__file__),'misc','jars'))], run_headless=True)
subsequent print javabridge.JARS is not showing the directory added.
How can I add a directory using class_path while starting jvm?

How can I also run the script in jvm DEBUG mode (-Xdebug)?

**Comment by narasing** [comment]
I tried using the absolute path as well 
javabridge.start_vm(class_path="/home/sysnyqcestg/misc/jars"). Result is same.

**Comment by LeeKamentsky** [comment]
Yup, not added to javabridge.JARS. But try this:

    import javabridge
    javabridge.start_vm(class_path=javabridge.JARS+["/home/sysnyqcestg/misc/jars"])
    print javabridge.JARS
    print javabridge.JClassWrapper("java.lang.System").getProperty("java.class.path")

You should see that javabridge.JARS remains the same (as it should be - it's just a list of what javabridge itself needs, but you should see your classpath added to what Java itself thinks is its classpath.

**Comment by narasing** [comment]
I see that java.class.path has the correct folder. But I still cannot find the class. Its able to find only when specific jar is added to the folder.I am on Java 1.6 . Also providing the property file still unable to find it.

['/home/sysnyqcestg/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/javabridge-1.0.11-py2.7-linux-x86_64.egg/javabridge/jars/rhino-1.7R4.jar', '/home/sysnyqcestg/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/javabridge-1.0.11-py2.7-linux-x86_64.egg/javabridge/jars/runnablequeue.jar', '/home/sysnyqcestg/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/javabridge-1.0.11-py2.7-linux-x86_64.egg/javabridge/jars/cpython.jar']
/home/sysnyqcestg/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/javabridge-1.0.11-py2.7-linux-x86_64.egg/javabridge/jars/rhino-1.7R4.jar:/home/sysnyqcestg/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/javabridge-1.0.11-py2.7-linux-x86_64.egg/javabridge/jars/runnablequeue.jar:/home/sysnyqcestg/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/javabridge-1.0.11-py2.7-linux-x86_64.egg/javabridge/jars/cpython.jar:/home/sysnyqcestg/mukkavin/misc/jars/TxJapi.jar:/home/sysnyqcestg/mukkavin/misc/jars/log4j-1.2.17.jar:/home/sysnyqcestg/mukkavin/misc/config/TxJApi.properties:/home/sysnyqcestg/mukkavin/misc/config/MEUAT.xml
Hello, world
log4j:WARN No appenders could be found for logger (com.barcap.tx.api.LogManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Failed to get class Lcom/barcap/tx/api/SessionFactory;
Exception in thread "Thread-0" java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: java.io.IOException: Unable to load api properties
        at com.barcap.tx.api.SessionFactory.<clinit>(SessionFactory.java:56)
Caused by: java.io.IOException: Unable to load api properties
        at com.barcap.tx.api.ApiSettings.<init>(ApiSettings.java:28)
        at com.barcap.tx.api.SessionFactory.<clinit>(SessionFactory.java:27)
Traceback (most recent call last):
  File "./ME_jxAPI.py", line 16, in <module>
    iSession = javabridge.static_call("Lcom/barcap/tx/api/SessionFactory;", "create", "(Ljava/lang/String;)V", "MEUAT")
  File "/home/sysnyqcestg/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/javabridge-1.0.11-py2.7-linux-x86_64.egg/javabridge/jutil.py", line 902, in static_call
    fn = make_static_call(class_name, method_name, sig)
  File "/home/sysnyqcestg/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/javabridge-1.0.11-py2.7-linux-x86_64.egg/javabridge/jutil.py", line 876, in make_static_call
    raise JavaException(jexception)

in the 3rd party jar, Its simple loading the /home/sysnyqcestg/mukkavin/misc/config/TxJApi.properties, which is available in classpath.

**Comment by LeeKamentsky** [comment]
I specify each jar individually in the classpath. I don't know if specifying a directory loads all jars in the directory.

 It looks like you have successfully loaded whatever jar houses the class, "com.barcap.tx.api.SessionFactory", so I am guessing the problem is on your end.

**Comment by narasing** [comment]
Once I provided jar instead of folder all the above options worked. 

But the error I get seems to be classpath related.TxJapi.properties is to be called by placing it in the CLASSPATH. TxJapi uses standard JDK function ClassLoader.getResourceAsStream(...) to load the properties file.Given that folders cannot be placed in the class_path but only JARS, properties file  is not found . Anyway around this?

thanks

**Comment by LeeKamentsky** [comment]
I'd separate the problem into three parts:
1) When you specify the class path using pure Java, does it work?
2) When you specify the class path using Javabridge, is the class path
substantially the same as in the pure Java case?
3) Does it work in Java and not work in Javabridge, even though the class
paths are substantially the same.

I think the problem is yours if the answer is "no" to either 1 or 2 and
it's a Javabridge bug if 3 - I would appreciate a complete description of
how to reproduce the bug if it turns out to be 3, something like this:
http://www.mkyong.com/java/java-read-a-file-from-resources-folder/

except pointed at the path to your properties file (and with a print
statement to show the java.class.path. Once you have that class, you can
run it both from java and the javabridge with the classpath arguments
(please post the output along with the arguments used to start Java).

**Comment by narasing** [comment]
Interestingly, putting a colon at the end of last jar file resolved the issue. 

javabridge.start_vm(class_path= javabridge.JARS + [jar file with path"] + [PATH/TxJapi.properties] + [] +  ["PATH/apache-log4j-extras-1.1.jar:"] colon at the end of the last jar file resolved it. While removing it cant find the properties file. 

Thanks for all the help.
