### ISSUE TITLE
BSD or GPL license

### ISSUE THREAD

**Issue by jakirkham** [CellProfiler/python-javabridge#56]
I am a bit confused as to what the license for this code is

 When looking at the license file ( https://github.com/CellProfiler/python-javabridge/blob/master/LICENSE ), it reads like a BSD license and the latest commit references BSD. However, these lines ( https://github.com/CellProfiler/python-javabridge/blob/master/LICENSE#L1-L2 ) suggest that some code may be under the GPL. Doing a quick search doesn't reveal anything in this project with "GPL" in it (other than those lines from the license). However, this statement is a bit disconcerting.

Is this actually BSD licensed in whole or is it not?

**Comment by LeeKamentsky** [comment]
Is in whole, thanks for pointing that out. CellProfiler, which uses python-javabridge is currently (until later this week when we move it to BSD) GPL, but python-javabridge is licensed as BSD in its entirety. Let me change that for you.

**Comment by jakirkham** [comment]
Thanks for clarifying, @LeeKamentsky.
