### ISSUE TITLE
Problem installing javabridge on Ubuntu 15.10 inside Anaconda

### ISSUE THREAD

**Issue by sebi06** [CellProfiler/python-javabridge#63]
Hi guys,

The numpy version is:

sebi06@sebi06-Lapto:~$ conda list numpy
# packages in environment at /home/sebi06/anaconda:
#
numpy                     1.10.1                   py27_0  
sebi06@sebi06-Lapto:~$ 

Then I just tried to install javabridge inside Anaconde via: pip install javabridge-1.0.11.tar.gz

sebi06@sebi06-Lapto:~$ pip install ~/Downloads/javabridge-1.0.11.tar.gz
Processing ./Downloads/javabridge-1.0.11.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy in ./anaconda/lib/python2.7/site-packages (from javabridge==1.0.11)
Building wheels for collected packages: javabridge
  Running setup.py bdist_wheel for javabridge
  Complete output from command /home/sebi06/anaconda/bin/python -c "import setuptools;__file__='/tmp/pip-uNk2Xg-build/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpWAb_DCpip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/javabridge
  copying javabridge/__init__.py -> build/lib.linux-x86_64-2.7/javabridge
  copying javabridge/locate.py -> build/lib.linux-x86_64-2.7/javabridge
  copying javabridge/_version.py -> build/lib.linux-x86_64-2.7/javabridge
  copying javabridge/wrappers.py -> build/lib.linux-x86_64-2.7/javabridge
  copying javabridge/jutil.py -> build/lib.linux-x86_64-2.7/javabridge
  copying javabridge/noseplugin.py -> build/lib.linux-x86_64-2.7/javabridge
  creating build/lib.linux-x86_64-2.7/javabridge/tests
  copying javabridge/tests/__init__.py -> build/lib.linux-x86_64-2.7/javabridge/tests
  copying javabridge/tests/test_javabridge.py -> build/lib.linux-x86_64-2.7/javabridge/tests
  copying javabridge/tests/test_wrappers.py -> build/lib.linux-x86_64-2.7/javabridge/tests
  copying javabridge/tests/test_cpython.py -> build/lib.linux-x86_64-2.7/javabridge/tests
  copying javabridge/tests/test_jutil.py -> build/lib.linux-x86_64-2.7/javabridge/tests
  creating build/lib.linux-x86_64-2.7/javabridge/jars
  copying javabridge/jars/test.jar -> build/lib.linux-x86_64-2.7/javabridge/jars
  copying javabridge/jars/rhino-1.7R4.jar -> build/lib.linux-x86_64-2.7/javabridge/jars
  copying javabridge/jars/cpython.jar -> build/lib.linux-x86_64-2.7/javabridge/jars
  copying javabridge/jars/runnablequeue.jar -> build/lib.linux-x86_64-2.7/javabridge/jars
  running build_ext
  javac -source 6 -target 6 /tmp/pip-uNk2Xg-build/java/org/cellprofiler/runnablequeue/RunnableQueue.java
  warning: [options] bootstrap class path not set in conjunction with -source 1.6
  1 warning
  jar cf /tmp/pip-uNk2Xg-build/build/lib.linux-x86_64-2.7/javabridge/jars/runnablequeue.jar -C /tmp/pip-uNk2Xg-build/java org/cellprofiler/runnablequeue/RunnableQueue.class -C /tmp/pip-uNk2Xg-build/java org/cellprofiler/runnablequeue/RunnableQueue$1.class
  javac -source 6 -target 6 /tmp/pip-uNk2Xg-build/java/org/cellprofiler/javabridge/test/RealRect.java
  warning: [options] bootstrap class path not set in conjunction with -source 1.6
  1 warning
  jar cf /tmp/pip-uNk2Xg-build/build/lib.linux-x86_64-2.7/javabridge/jars/test.jar -C /tmp/pip-uNk2Xg-build/java org/cellprofiler/javabridge/test/RealRect.class
  javac -source 6 -target 6 /tmp/pip-uNk2Xg-build/java/org/cellprofiler/javabridge/CPython.java /tmp/pip-uNk2Xg-build/java/org/cellprofiler/javabridge/CPythonInvocationHandler.java
  warning: [options] bootstrap class path not set in conjunction with -source 1.6
  Note: /tmp/pip-uNk2Xg-build/java/org/cellprofiler/javabridge/CPythonInvocationHandler.java uses unchecked or unsafe operations.
  Note: Recompile with -Xlint:unchecked for details.
  1 warning
  jar cf /tmp/pip-uNk2Xg-build/build/lib.linux-x86_64-2.7/javabridge/jars/cpython.jar -C /tmp/pip-uNk2Xg-build/java org/cellprofiler/javabridge/CPython.class -C /tmp/pip-uNk2Xg-build/java org/cellprofiler/javabridge/CPython$WrappedException.class -C /tmp/pip-uNk2Xg-build/java org/cellprofiler/javabridge/CPython$StackFrame.class -C /tmp/pip-uNk2Xg-build/java org/cellprofiler/javabridge/CPythonInvocationHandler.class -C /tmp/pip-uNk2Xg-build/java org/cellprofiler/javabridge/CPythonInvocationHandler.class
  building 'javabridge._javabridge' extension
  creating build/temp.linux-x86_64-2.7
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sebi06/anaconda/lib/python2.7/site-packages/numpy/core/include -I/usr/lib/jvm/java-8-openjdk-amd64/include -I/usr/lib/jvm/java-8-openjdk-amd64/include/linux -I/home/sebi06/anaconda/include/python2.7 -c _javabridge.c -o build/temp.linux-x86_64-2.7/_javabridge.o
  In file included from /home/sebi06/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1781:0,
                   from /home/sebi06/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                   from /home/sebi06/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from _javabridge.c:346:
  /home/sebi06/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^
  _javabridge.c:348:17: fatal error: jni.h: Datei oder Verzeichnis nicht gefunden
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for javabridge
Failed to build javabridge
Installing collected packages: javabridge
  Running setup.py install for javabridge
    Complete output from command /home/sebi06/anaconda/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-uNk2Xg-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-BKNivl-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running build_ext
    javac -source 6 -target 6 /tmp/pip-uNk2Xg-build/java/org/cellprofiler/runnablequeue/RunnableQueue.java
    warning: [options] bootstrap class path not set in conjunction with -source 1.6
    1 warning
    javac -source 6 -target 6 /tmp/pip-uNk2Xg-build/java/org/cellprofiler/javabridge/test/RealRect.java
    warning: [options] bootstrap class path not set in conjunction with -source 1.6
    1 warning
    javac -source 6 -target 6 /tmp/pip-uNk2Xg-build/java/org/cellprofiler/javabridge/CPython.java /tmp/pip-uNk2Xg-build/java/org/cellprofiler/javabridge/CPythonInvocationHandler.java
    warning: [options] bootstrap class path not set in conjunction with -source 1.6
    Note: /tmp/pip-uNk2Xg-build/java/org/cellprofiler/javabridge/CPythonInvocationHandler.java uses unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    1 warning
    building 'javabridge._javabridge' extension
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sebi06/anaconda/lib/python2.7/site-packages/numpy/core/include -I/usr/lib/jvm/java-8-openjdk-amd64/include -I/usr/lib/jvm/java-8-openjdk-amd64/include/linux -I/home/sebi06/anaconda/include/python2.7 -c _javabridge.c -o build/temp.linux-x86_64-2.7/_javabridge.o
    In file included from /home/sebi06/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1781:0,
                     from /home/sebi06/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /home/sebi06/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from _javabridge.c:346:
    /home/sebi06/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    _javabridge.c:348:17: fatal error: jni.h: Datei oder Verzeichnis nicht gefunden
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/sebi06/anaconda/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-uNk2Xg-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-BKNivl-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-uNk2Xg-build
sebi06@sebi06-Lapto:~$

**Comment by LeeKamentsky** [comment]
That's a bit bizarre. The command that builds _javabridge.o references your JDK: `gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sebi06/anaconda/lib/python2.7/site-packages/numpy/core/include` **`-I/usr/lib/jvm/java-8-openjdk-amd64/include`** `-I/usr/lib/jvm/java-8-openjdk-amd64/include/linux -I/home/sebi06/anaconda/include/python2.7 -c _javabridge.c -o build/temp.linux-x86_64-2.7/_javabridge.o`

Can you see `jni.h` in `/usr/lib/jvm/java-8-openjdk-amd64/include`?

**Comment by sebi06** [comment]
Hi Lee,

this solved the problem. I re-installed opbejdk, because the include folder was missing. The rest was there... (strange). Now it works. Thanks, Sebi
