### ISSUE TITLE
Use of wrapper classes in ipython causes Java Exceptions

### ISSUE THREAD

**Issue by jbcoe** [CellProfiler/python-javabridge#72]
Running the following code in ipython leads to a java exception
```
import javabridge
javabridge.start_vm(run_headless=True)
a = javabridge.JWrapper(javabridge.make_instance("java/util/ArrayList","()V"))
a
```

I would hope that `a` on its own would call the __repr__ method and show the array but instead it give a java exception:

```
Exception in thread "Thread-1" java.lang.NoSuchFieldException: _ipython_display_
        at java.lang.Class.getField(Class.java:1690)
Out[4]: Instance of java.util.ArrayList: []
```

A user-defined class without _ipython_display_ defined works as expected. I'm not sure where the problem lies but the ability to wrap Java classes in python in an interactive session is awesome and it would be worth getting it working nicely.

I've posted a parallel issue on ipython as I'm not sure where changes need making: https://github.com/ipython/ipython/issues/9253

**Comment by LeeKamentsky** [comment]
Cool idea. I am betting that the wrapper class should be translating the Java exception in this case into an AttributeError exception or similar and I'd bet that IPython is expecting to catch that and then do the repr. Also, repr should be calling a.toString() - right? A pull request for the change would be much appreciated.

BTW. Maybe you want to do this instead of using make_instance :wink: :

    a = javabridge.JClassWrapper("java.util.ArrayList")()

**Comment by takluyver** [comment]
Spot on - IPython is checking for a method that may exist, and is ready to catch AttributeError and fall back to other methods if it doesn't.

**Comment by LeeKamentsky** [comment]
Oh, regarding the `__repr__` stuff, `__str__ calls o.toString()`, `__repr__` does a little more: it tells you the class and then appends the output of o.toString(). Try this:

    > a = javabridge.JClassWrapper('java.util.ArrayList')()
    > a.add("Foo")
    > a
    Instance of java.util.ArrayList: [foo]

I think I'd like to keep the current __repr__ behavior.

**Comment by takluyver** [comment]
I think it's a good idea to keep the extra info in the repr; without it you could easily think that was a native Python list.
