### ISSUE TITLE
Difference between this and `javabridge` on PyPI

### ISSUE THREAD

**Issue by raivivek** [CellProfiler/python-javabridge#8]
Hi, it looks like there are two versions of the same package (both point to same GitHub dev url) on PyPI — `javabridge` and `python-javabridge`. The latter has been updated to v4.0 but former has not been. I'm a little confused as to which package will be more appropriate for CellProfiler going forward? Thanks for all the work.

**Comment by DavidStirling** [comment]
Hi @raivivek,

The `python-javabridge` package is our fork, which is being maintained with code oriented towards use with CellProfiler 4 (Python 3). Older versions of CellProfiler running on Python 2 should still operate with the original `javabridge` package.

**Comment by jakirkham** [comment]
If one installs both in the same environment, what happens? Do they conflict at all? Or are they using different namespaces?

**Comment by DavidStirling** [comment]
I expect that they'll conflict as both are imported as `javabridge`. However, the changes in our fork are primarily geared towards locating the java installation bundled with built versions of CellProfiler. If there's a valid java installation pointed to by the `JAVA_HOME` environment variable then it's quite possible that either version would work with CellProfiler.

**Comment by raivivek** [comment]
Thanks for the clarification @DavidStirling!
